name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Corrected to a valid and modern SDK range

dependencies:
  flutter:
    sdk: flutter

  # --- Your Added Packages ---
  http: ^1.2.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_sound: ^9.3.0
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  intl: ^0.19.0

  # --- Default Icon Package (Duplicate Removed) ---
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true